### ISSUE TITLE
请问这个有什么用？

### ISSUE THREAD

**Issue by ArtificialZeng** [xw5xr6/revTongYi#1]
请问这个有什么用？

**Comment by xw5xr6** [comment]
阿里 通义千问 AI对话网站逆向工程

**Comment by ArtificialZeng** [comment]
> 阿里 通义千问 AI对话网站逆向工程

求教 具体怎么逆向，逆向出来的是什么

**Comment by xw5xr6** [comment]
> > 阿里 通义千问 AI对话网站逆向工程
> 
> 求教 具体怎么逆向，逆向出来的是什么

此库使你可以通过python与阿里通义千问交互，具体使用方式请查看本仓库README
