### ISSUE TITLE
[Bug] TypeError报错

### ISSUE THREAD

**Issue by Huasushis** [xw5xr6/revTongYi#6]
- 运行环境：Windows11
- 代码：readme 中的示例代码
- 报错：
    - File "E:\Anaconda3\lib\site-packages\revTongYi\__init__.py", line 8, in <module>
    from . import qianwen
  File "E:\Anaconda3\lib\site-packages\revTongYi\qianwen.py", line 20, in <module>
    class Chatbot:
  File "E:\Anaconda3\lib\site-packages\revTongYi\qianwen.py", line 224, in Chatbot
    ) -> typing.Generator[dict, None, None] | dict:
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'type'

**Comment by Huasushis** [comment]
问题已解决，原因是 python3.9 不支持这种运算符，可以将其改为 typing.Union()。

另外，再更低的 python 版本下 list[int] 也会报错，可以更改为 typing.List[int] 来解决。

**Comment by xw5xr6** [comment]
已在 v0.0.3.3 修复此问题
